simulation_time: 48
warm_up_time: 0
server_side:
    n_projects: 1
    sprojects:
      - snumber: 0
        name: RakeSearchtype2e13@home
        nscheduling_servers: 1
        ndata_servers: 1
        ndata_client_servers: 1
        server_pw: 12000000000f
        disk_bw: 167772160
        ifgl_percentage: 100
        ifcd_percentage: 100
        averagewpif: 1
        input_file_size: 1024
        task_fpops: 2000000000000
        output_file_size: 11000
        min_quorum: 1
        target_nresults: 1
        max_error_results: 10000
        max_total_results: 10
        max_success_results: 8
        delay_bound: 3600
        output_file_storage: 0
        dsreplication: 1
        dcreplication: 1
client_side:
    n_groups: 2
    groups:
      - n_clients: 100
        ndata_clients: 1
        connection_interval: 3600
        scheduling_interval: 3600
        gbw: 50Mbps
        glatency: 7.3ms
        traces_file: /Traces/boom_host_cpu
        max_speed: 0.5
        min_speed: 0.1
        pv_distri: 5
        pa_param: 0.0534
        pb_param: 0.9
        db_traces_file: /Traces/storage/boom_disk_capacity
        db_distri: 5
        da_param: 21.086878916910564
        db_param: 159.1597190181666
        av_distri: 6
        aa_param: 0.357
        ab_param: 43.652
        nv_distri: 7
        na_param: 0.15
        nb_param: 1
        att_projs: 1
        gprojects:
          - pnumber: 0
            priority: 2
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 95
            canonical_percentage: 99
      - n_clients: 100
        ndata_clients: 1
        connection_interval: 3600
        scheduling_interval: 3600
        gbw: 50Mbps
        glatency: 7.3ms
        traces_file: /Traces/boom_host_cpu
        max_speed: 200
        min_speed: 60
        pv_distri: 5
        pa_param: 0.0534
        pb_param: 0.9
        db_traces_file: /Traces/storage/boom_disk_capacity
        db_distri: 5
        da_param: 21.086878916910564
        db_param: 159.1597190181666
        av_distri: 6
        aa_param: 0.357
        ab_param: 43.652
        nv_distri: 7
        na_param: 0.15
        nb_param: 1
        att_projs: 1
        gprojects:
          - pnumber: 0
            priority: 2
            lsbw: 10Gbps
            lslatency: 50us
            ldbw: 2Mbps
            ldlatency: 50us
            success_percentage: 95
            canonical_percentage: 80
experiment_run:
    timeline:
        execute_state_log_path:  /home/ubuntu/combos_cpp_shadow_new/experiments/many_invalid/execute_stat_80.csv 
        observable_clients:  c10,c20 
    seed_for_deterministic_run:  6523446 
    measures:
        clean_before_write:  true 
        save_filepath:  /home/ubuntu/combos_cpp_shadow_new/experiments/many_invalid/save_file.txt 
